### ISSUE TITLE
軽量の VM Box を探す

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-vagrant#2]
puppetlabs/centos-6.6-32-nocm はサイズが大きい上に、回線が遅そうなので、軽量かつ短時間でダウンロードできるものを探す

**Comment by poego** [comment]
ちょっとしらべてみました。 chef/centos-6.6 が良さそうです。  
32bit用もあります。

+ puppetlabs/centos-6.6-32-nocm   
546MB
+ [chef/centos-6.6](https://atlas.hashicorp.com/chef/boxes/centos-6.6)  
234MB 
+ [chef/centos-6.6-i386](https://atlas.hashicorp.com/chef/boxes/centos-6.6-i386)  
220MB
