### ISSUE TITLE
PHPバージョンの切替はブランチで

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-vagrant#5]
現在、 PHP5.3 の設定がコメントアウトされているため、ブランチ切替で対応できるようにする

**Comment by Yangsin** [comment]
できるだけ、PHPのバージョン切替くらいは、テキストエディタでちょっと修正すればOKくらいにしておきたいですね。
ブランチで切り替えるとかになると、他の部分を変えた時に修正を全ブランチで反映するなどが必要になり、利用するブランチはMasterだけにしておくほうが、利用者のハードルが下がると考えています。

**Comment by nanasess** [comment]
ソースを開いて変更箇所を探して修正するより、 ```git checkout``` 一発の方が楽な気もしますが、好みの問題ですね。
バージョン切替で、ほかの箇所も修正しなくてはいけなくなったりする可能性もありますし、 PHP5.3 で作業していて、 Pull Request したくなっても、いちいち ```git stash``` しなくてはならなかったりするので、個人的にはブランチにした方が、今後の利便性は上がると思います。

**Comment by Yangsin** [comment]
やり方は悩むところなのですが、
利用者のイメージとして、現状は、Gitで何かを切り替えるということになれている方より、エディタで環境に合わせてゴニョゴニョするほうが慣れている方が慣れているかたが多いだろうと思ってます。
ブランチ毎にバラバラにするよりは、まずはブランチ1つの便利なものを提供したく。

**Comment by nanasess** [comment]
#19 で、複数PHPバージョンのサポートは止めてしまったのでクローズします。
