### ISSUE TITLE
PHPUnit のレシピ追加

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-vagrant#6]
PHPUnit のレシピも追加し、ユニットテストの環境も整えられるようにする

**Comment by nanasess** [comment]
EC-CUBE の composer に含まれていましたっけ...

**Comment by poego** [comment]
Composerにはいってますね。
https://github.com/EC-CUBE/ec-cube/blob/eccube-3.0.0-beta/composer.json#L62

**Comment by nanasess** [comment]
含まれているということで、こちらはclose します。
